spring:
  datasource:
    url: jdbc:mysql://localhost:3306/examination?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

mybatis:
  type-aliases-package: com.examination.model          # 定义所有操作类的别名所在包
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true